openapi: 3.0.0
info:
  title: Yamada-Ikueikai-Admin
  version: '1.0'
  description: 採用側システムのAPI
servers:
  - url: 'http://localhost:3000'
paths:
  /applicants:
    get:
      summary: 応募者一覧の取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                items:
                  $ref: '#/components/schemas/applicant'
              examples:
                example-1:
                  value:
                    - create_date: '2020-07-27T15:49:59.069Z'
                      update_date: '2020-07-30T15:49:59.069Z'
                      user_id: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
                      year: '2020'
                      first_name:
                        kanji: 山田
                        furigana: やまだ
                      last_name:
                        kanji: 太郎
                        furigana: たろう
                      school:
                        graduate_school: 育英大学院
                        university: 育英大学
                        course: ○○学部
                        major: ○○学科
                      housing: 大阪市北区中崎西2-4-12 梅田センタービル
                      myself:
                        postal_code: '5308323'
                        address: 大阪市北区中崎西2-4-12 梅田センタービル
                        telephone: '0123456789'
                        email_address: yamada@ikuei.com
                      parent:
                        postal_code: '5308323'
                        address: 大阪市北区中崎西2-4-12 梅田センタービル
                        telephone: '0123456789'
                        email_address: yamada@ikuei.com
                      birthday: '19970527'
                      benefit_period:
                        start: '202004'
                        end: '202203'
                      educational_background:
                        high_school_admission:
                          year_month: '201304'
                          name: 山田高校
                          department: 普通科
                        high_school_graduation:
                          year_month: '201603'
                          name: 山田高校
                          department: 普通科
                        university_admission:
                          year_month: '201604'
                          name: 山田大学
                          department: ○○学科
                        university_graduation:
                          year_month: '202003'
                          name: 山田大学
                          department: ○○学科
                        graduate_school_admission:
                          year_month: '202004'
                          name: 山田大学院
                          department: ○○学科
                      hobbies: サッカー
                      skills: サッカー
                      family:
                        - name: 山田一
                          relationship: 父
                          age: '50'
                        - name: 山田花子
                          relationship: 母
                          age: '40'
                      result: 0
                      send_mail: true
                      status: 0
                      scholarship_type: 1
      operationId: get-admin-aplicants
      parameters: []
      tags:
        - Applicants
    parameters: []
  '/applicants/{user_id}':
    parameters:
      - schema:
          type: string
        name: user_id
        in: path
        required: true
    get:
      summary: 応募者情報の取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicant'
              examples:
                example-1:
                  value:
                    create_date: '2020-07-27T15:49:59.069Z'
                    update_date: '2020-07-30T15:49:59.069Z'
                    user_id: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
                    year: '2020'
                    first_name:
                      kanji: 山田
                      furigana: やまだ
                    last_name:
                      kanji: 太郎
                      furigana: たろう
                    school:
                      graduate_school: 育英大学院
                      university: 育英大学
                      course: ○○学部
                      major: ○○学科
                    housing: 大阪市北区中崎西2-4-12 梅田センタービル
                    myself:
                      postal_code: '5308323'
                      address: 大阪市北区中崎西2-4-12 梅田センタービル
                      telephone: '0123456789'
                      email_address: yamada@ikuei.com
                    parent:
                      postal_code: '5308323'
                      address: 大阪市北区中崎西2-4-12 梅田センタービル
                      telephone: '0123456789'
                      email_address: yamada@ikuei.com
                    birthday: '19970527'
                    benefit_period:
                      start: '202004'
                      end: '202203'
                    educational_background:
                      high_school_admission:
                        year_month: '201304'
                        name: 山田高校
                        department: 普通科
                      high_school_graduation:
                        year_month: '201603'
                        name: 山田高校
                        department: 普通科
                      university_admission:
                        year_month: '201604'
                        name: 山田大学
                        department: ○○学科
                      university_graduation:
                        year_month: '202003'
                        name: 山田大学
                        department: ○○学科
                      graduate_school_admission:
                        year_month: '202004'
                        name: 山田大学院
                        department: ○○学科
                    hobbies: サッカー
                    skills: サッカー
                    family:
                      - name: 山田一
                        relationship: 父
                        age: '50'
                      - name: 山田花子
                        relationship: 母
                        age: '40'
                    result: 0
                    send_mail: true
                    status: 0
                    scholarship_type: 1
      operationId: get-applicants-id
      parameters: []
      tags:
        - Applicants
    put:
      summary: 応募者情報の更新
      operationId: put-applicants-id
      responses:
        '200':
          description: OK
      description: |-
        クエリなしの場合は全項目を更新
        result クエリ文字列がある場合には合否結果のみ更新
      parameters:
        - schema:
            type: integer
            enum:
              - 0
              - 1
              - 2
          in: query
          name: result
          description: '合否結果（0:未, 1:採用, 2:不採用）'
      tags:
        - Applicants
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/applicant'
            examples:
              example-1:
                value:
                  create_date: '2020-07-27T15:49:59.069Z'
                  update_date: '2020-07-30T15:49:59.069Z'
                  user_id: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
                  year: '2020'
                  first_name:
                    kanji: 山田
                    furigana: やまだ
                  last_name:
                    kanji: 太郎
                    furigana: たろう
                  school:
                    graduate_school: 育英大学院
                    university: 育英大学
                    course: ○○学部
                    major: ○○学科
                  housing: 大阪市北区中崎西2-4-12 梅田センタービル
                  myself:
                    postal_code: '5308323'
                    address: 大阪市北区中崎西2-4-12 梅田センタービル
                    telephone: '0123456789'
                    email_address: yamada@ikuei.com
                  parent:
                    postal_code: '5308323'
                    address: 大阪市北区中崎西2-4-12 梅田センタービル
                    telephone: '0123456789'
                    email_address: yamada@ikuei.com
                  birthday: '19970527'
                  benefit_period:
                    start: '202004'
                    end: '202203'
                  educational_background:
                    high_school_admission:
                      year_month: '201304'
                      name: 山田高校
                      department: 普通科
                    high_school_graduation:
                      year_month: '201603'
                      name: 山田高校
                      department: 普通科
                    university_admission:
                      year_month: '201604'
                      name: 山田大学
                      department: ○○学科
                    university_graduation:
                      year_month: '202003'
                      name: 山田大学
                      department: ○○学科
                    graduate_school_admission:
                      year_month: '202004'
                      name: 山田大学院
                      department: ○○学科
                  hobbies: サッカー
                  skills: サッカー
                  family:
                    - name: 山田一
                      relationship: 父
                      age: '50'
                    - name: 山田花子
                      relationship: 母
                      age: '40'
                  result: 0
                  send_mail: true
                  status: 0
                  scholarship_type: 1
    delete:
      summary: 応募者情報の削除
      operationId: delete-applicants-id
      responses:
        '200':
          description: OK
      parameters: []
      tags:
        - Applicants
  /master:
    get:
      summary: マスター情報一覧の取得
      tags:
        - Master
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/master'
              examples:
                example-1:
                  value:
                    - year: '2020'
                      apprication_period:
                        start: '20200401'
                        end: '20200531'
                      ammount:
                        master: '10000'
                        bachelor: '10000'
                      number:
                        master: '10'
                        bachelor: '10'
      operationId: get-master-list
      parameters: []
  '/master/{year}':
    get:
      summary: マスター情報の取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/master'
              examples:
                example-1:
                  value:
                    year: '2020'
                    apprication_period:
                      start: '20200401'
                      end: '20200531'
                    ammount:
                      master: '10000'
                      bachelor: '10000'
                    number:
                      master: '10'
                      bachelor: '10'
      operationId: get-master
      parameters: []
      tags:
        - Master
    put:
      summary: マスター情報の更新
      operationId: put-master
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/master'
            examples:
              example-1:
                value:
                  year: '2020'
                  apprication_period:
                    start: '20200401'
                    end: '20200531'
                  ammount:
                    master: '10000'
                    bachelor: '10000'
                  number:
                    master: '10'
                    bachelor: '10'
      parameters: []
      tags:
        - Master
    parameters:
      - schema:
          type: string
        name: year
        in: path
        required: true
  /mail:
    post:
      summary: 合格者にメールを送信
      operationId: post-mail
      responses:
        '200':
          description: OK
      parameters:
        - schema:
            type: string
            enum:
              - accept
              - reject
          in: query
          name: dest
          description: ''
          required: true
  '/applicants/object_presigned_url/{user_id}':
    get:
      summary: S3 オブジェクトの署名付きURLの取得
      tags:
        - Applicants
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: ''
                properties:
                  url:
                    type: string
                    description: S3の署名付きURL
              examples:
                example-1:
                  value:
                    url: 'https://YOUR_BUCKET.s3.amazonaws.com/YOUR_KEY'
      operationId: get-presigned_url
      parameters:
        - schema:
            type: string
            deprecated: false
            enum:
              - photo
              - report
              - income_certificat
              - recommendation
          in: query
          name: object
          required: true
          description: 本人写真、論文、所得証明書、推薦状のオブジェクトを操作
        - schema:
            type: string
            enum:
              - get
              - put
          in: query
          name: clientMethod
          required: true
          description: ダウンロードURL生成時はget. アップロードURL生成時はput
        - schema:
            type: string
          in: query
          name: filetype
          description: 'clientMethod="put" のときアップロードするファイルの形式を指定する。clientMethod="get" のときは指定しても無視される。'
      description: S3オブジェクトの署名付きURLの取得
    parameters:
      - schema:
          type: string
        name: user_id
        in: path
        required: true
  /archive:
    post:
      summary: データのアーカイブ移行
      operationId: post-archive
      responses:
        '200':
          description: OK
      parameters: []
      description: ''
components:
  schemas:
    applicant:
      x-examples:
        example-1:
          create_date: '2020-07-27T15:49:59.069Z'
          update_date: '2020-07-30T15:49:59.069Z'
          user_id: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
          year: '2020'
          first_name:
            kanji: 山田
            furigana: やまだ
          last_name:
            kanji: 太郎
            furigana: たろう
          school:
            graduate_school: 育英大学院
            university: 育英大学
            course: ○○学部
            major: ○○学科
          housing: 大阪市北区中崎西2-4-12 梅田センタービル
          myself:
            postal_code: '5308323'
            address: 大阪市北区中崎西2-4-12 梅田センタービル
            telephone: '0123456789'
            email_address: yamada@ikuei.com
          parent:
            postal_code: '5308323'
            address: 大阪市北区中崎西2-4-12 梅田センタービル
            telephone: '0123456789'
            email_address: yamada@ikuei.com
          birthday: '19970527'
          benefit_period:
            start: '202004'
            end: '202203'
          educational_background:
            high_school_admission:
              year_month: '201304'
              name: 山田高校
              department: 普通科
            high_school_graduation:
              year_month: '201603'
              name: 山田高校
              department: 普通科
            university_admission:
              year_month: '201604'
              name: 山田大学
              department: ○○学科
            university_graduation:
              year_month: '202003'
              name: 山田大学
              department: ○○学科
            graduate_school_admission:
              year_month: '202004'
              name: 山田大学院
              department: ○○学科
          hobbies: サッカー
          skills: サッカー
          family:
            - name: 山田一
              relationship: 父
              age: '50'
            - name: 山田花子
              relationship: 母
              age: '40'
          result: 0
          send_mail: true
          status: 0
          scholarship_type: 1
      title: applicant
      type: object
      properties:
        create_date:
          type: string
        update_date:
          type: string
        user_id:
          type: string
        year:
          type: string
        first_name:
          type: object
          properties:
            kanji:
              type: string
            furigana:
              type: string
        last_name:
          type: object
          properties:
            kanji:
              type: string
            furigana:
              type: string
        school:
          type: object
          properties:
            graduate_school:
              type: string
            university:
              type: string
            course:
              type: string
            major:
              type: string
        housing:
          type: string
        myself:
          type: object
          properties:
            postal_code:
              type: string
            address:
              type: string
            telephone:
              type: string
            email_address:
              type: string
        parent:
          type: object
          properties:
            postal_code:
              type: string
            address:
              type: string
            telephone:
              type: string
            email_address:
              type: string
        birthday:
          type: string
        benefit_period:
          type: object
          properties:
            start:
              type: string
            end:
              type: string
        educational_background:
          type: object
          properties:
            high_school_graduation:
              type: object
              properties:
                year_month:
                  type: string
                name:
                  type: string
                department:
                  type: string
            university_admission:
              type: object
              properties:
                year_month:
                  type: string
                name:
                  type: string
                department:
                  type: string
            university_graduation:
              type: object
              properties:
                year_month:
                  type: string
                name:
                  type: string
                department:
                  type: string
            graduate_school_admission:
              type: object
              properties:
                year_month:
                  type: string
                name:
                  type: string
                department:
                  type: string
        hobbies:
          type: string
        skills:
          type: string
        family:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              relationship:
                type: string
              age:
                type: string
        result:
          type: integer
        send_mail:
          type: boolean
        status:
          type: integer
        scholarship_type:
          type: integer
    master:
      x-examples:
        example-1:
          year: '2020'
          apprication_period:
            start: '20200401'
            end: '20200531'
          ammount:
            master: '10000'
            bachelor: '10000'
          number:
            master: '10'
            bachelor: '10'
      title: master
      type: object
      properties:
        year:
          type: string
        apprication_period:
          type: object
          properties:
            start:
              type: string
            end:
              type: string
        ammount:
          type: object
          properties:
            master:
              type: string
            bachelor:
              type: string
        number:
          type: object
          properties:
            master:
              type: string
            bachelor:
              type: string
